syntax = "proto3";

package rentar.vehicle.v1;

import "google/protobuf/timestamp.proto";

service VehicleService {
  rpc ListVehicles(ListVehiclesRequest) returns (ListVehiclesResponse);
  rpc GetVehicle(GetVehicleRequest) returns (VehicleResponse);
  rpc CheckAvailability(CheckAvailabilityRequest) returns (ListVehiclesResponse);

  rpc CreateVehicle(CreateVehicleRequest) returns (VehicleResponse);
  rpc UpdateVehicle(UpdateVehicleRequest) returns (VehicleResponse);
  rpc DeactivateVehicle(DeactivateVehicleRequest) returns (VehicleResponse);

  rpc UpdateVehicleStatus(UpdateVehicleStatusRequest) returns (VehicleResponse);
}

enum VehicleType {
  VEHICLE_TYPE_UNSPECIFIED = 0;
  VEHICLE_TYPE_SEDAN = 1;
  VEHICLE_TYPE_SUV = 2;
  VEHICLE_TYPE_PICKUP = 3;
  VEHICLE_TYPE_COUPE = 4;
  VEHICLE_TYPE_HATCHBACK = 5;
}

enum VehicleStatus {
  VEHICLE_STATUS_UNSPECIFIED = 0;
  VEHICLE_STATUS_DISPONIBLE = 1;
  VEHICLE_STATUS_RESERVADO = 2;
  VEHICLE_STATUS_EN_ALQUILER = 3;
}

message Vehicle {
  int32 id = 1;
  string patente = 2;
  string marca = 3;
  string modelo = 4;
  int32 anio = 5;
  string color = 6;
  VehicleType tipo_vehiculo = 7;
  int64 precio_diario_centavos = 8;
  VehicleStatus estado = 9;
  bool activo = 10;
}

message VehicleFilter {
  VehicleType tipo_vehiculo = 1;
  string marca = 2;
  string modelo = 3;
  int64 precio_min_centavos = 4;
  int64 precio_max_centavos = 5;
}

message ListVehiclesRequest {
  bool solo_activos = 1;
  VehicleFilter filters = 2;
}

message ListVehiclesResponse {
  repeated Vehicle vehiculos = 1;
}

message GetVehicleRequest {
  int32 id = 1;
}

message CheckAvailabilityRequest {
  google.protobuf.Timestamp fecha_inicio = 1;
  google.protobuf.Timestamp fecha_fin = 2;
  VehicleFilter filtros = 3;
}

message CreateVehicleRequest {
  string patente = 1;
  string marca = 2;
  string modelo = 3;
  int32 anio = 4;
  string color = 5;
  VehicleType tipo_vehiculo = 6;
  int64 precio_diario_centavos = 7;
}

message UpdateVehicleRequest {
  int32 id = 1;
  string marca = 2;
  string modelo = 3;
  int32 anio = 4;
  string color = 5;
  VehicleType tipo_vehiculo = 6;
  int64 precio_diario_centavos = 7;
  bool activo = 8;
}

message DeactivateVehicleRequest {
  int32 id = 1;
}

message UpdateVehicleStatusRequest {
  int32 id = 1;
  VehicleStatus estado = 2;
}

message VehicleResponse {
  Vehicle vehiculo = 1;
}