# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rental_pb2 as rental__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rental_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RentalServiceStub:
    """=========================================================
    Servicio
    =========================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRental = channel.unary_unary(
                '/rentar.rental.v1.RentalService/CreateRental',
                request_serializer=rental__pb2.CreateRentalRequest.SerializeToString,
                response_deserializer=rental__pb2.RentalResponse.FromString,
                _registered_method=True)
        self.CancelRental = channel.unary_unary(
                '/rentar.rental.v1.RentalService/CancelRental',
                request_serializer=rental__pb2.CancelRentalRequest.SerializeToString,
                response_deserializer=rental__pb2.RentalResponse.FromString,
                _registered_method=True)
        self.GetRentalById = channel.unary_unary(
                '/rentar.rental.v1.RentalService/GetRentalById',
                request_serializer=rental__pb2.GetRentalByIdRequest.SerializeToString,
                response_deserializer=rental__pb2.RentalResponse.FromString,
                _registered_method=True)
        self.ListRentalsByCustomer = channel.unary_unary(
                '/rentar.rental.v1.RentalService/ListRentalsByCustomer',
                request_serializer=rental__pb2.ListRentalsByCustomerRequest.SerializeToString,
                response_deserializer=rental__pb2.ListRentalsResponse.FromString,
                _registered_method=True)
        self.CheckAvailability = channel.unary_unary(
                '/rentar.rental.v1.RentalService/CheckAvailability',
                request_serializer=rental__pb2.CheckAvailabilityRequest.SerializeToString,
                response_deserializer=rental__pb2.CheckAvailabilityResponse.FromString,
                _registered_method=True)


class RentalServiceServicer:
    """=========================================================
    Servicio
    =========================================================
    """

    def CreateRental(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRental(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRentalById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRentalsByCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RentalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRental': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRental,
                    request_deserializer=rental__pb2.CreateRentalRequest.FromString,
                    response_serializer=rental__pb2.RentalResponse.SerializeToString,
            ),
            'CancelRental': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRental,
                    request_deserializer=rental__pb2.CancelRentalRequest.FromString,
                    response_serializer=rental__pb2.RentalResponse.SerializeToString,
            ),
            'GetRentalById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRentalById,
                    request_deserializer=rental__pb2.GetRentalByIdRequest.FromString,
                    response_serializer=rental__pb2.RentalResponse.SerializeToString,
            ),
            'ListRentalsByCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRentalsByCustomer,
                    request_deserializer=rental__pb2.ListRentalsByCustomerRequest.FromString,
                    response_serializer=rental__pb2.ListRentalsResponse.SerializeToString,
            ),
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=rental__pb2.CheckAvailabilityRequest.FromString,
                    response_serializer=rental__pb2.CheckAvailabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rentar.rental.v1.RentalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rentar.rental.v1.RentalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RentalService:
    """=========================================================
    Servicio
    =========================================================
    """

    @staticmethod
    def CreateRental(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rentar.rental.v1.RentalService/CreateRental',
            rental__pb2.CreateRentalRequest.SerializeToString,
            rental__pb2.RentalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRental(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rentar.rental.v1.RentalService/CancelRental',
            rental__pb2.CancelRentalRequest.SerializeToString,
            rental__pb2.RentalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRentalById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rentar.rental.v1.RentalService/GetRentalById',
            rental__pb2.GetRentalByIdRequest.SerializeToString,
            rental__pb2.RentalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRentalsByCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rentar.rental.v1.RentalService/ListRentalsByCustomer',
            rental__pb2.ListRentalsByCustomerRequest.SerializeToString,
            rental__pb2.ListRentalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rentar.rental.v1.RentalService/CheckAvailability',
            rental__pb2.CheckAvailabilityRequest.SerializeToString,
            rental__pb2.CheckAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
